### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by SoftologyPro** [jianzongwu/DiffSensei#1]
After I install (137 GB), I launch the UI, click the first example and it shows this...

![image](https://github.com/user-attachments/assets/409c34f3-5bf0-4145-a4ca-1e1b9a46c1b1)

What do I do now?  Clicking either "End drawing IP BBox" and/or "Generate Images" gives error.

Thanks for any tips.

**Comment by SoftologyPro** [comment]
So I draw 2 squares in the left IP Box and click End Drawing IP BBOx which then draws them in red in the right box.  Then click Generate.

![image](https://github.com/user-attachments/assets/4d75aba7-098c-4a34-9ac0-2fc691292d35)

Am I missing anything?  I tried to then draw 2 more squares for dialog, but when I click Generate it complains
`ValueError: `ip_images` must have the same length as `ip_bbox`. But they are in length 2 and 4!`

![image](https://github.com/user-attachments/assets/6c25800b-0a84-48da-a608-7777a5ac4f81)

**Comment by SoftologyPro** [comment]
> In my understanding, the "End Drawing IP BBox" button is designed to help verify the areas you’ve designated as IP regions while drawing dialog bounding boxes on the right side.

So what steps do I need to take to generate bounding boxes and dialog boxes?  The instructions at the top of the UI say
"Upload manga character images, draw IP bounding boxes (should be the same number of uploaded images), click 'End Drawing IP Bbox', draw dialog bounding boxes, and click Generaet (typo) Images."

**Comment by jianzongwu** [comment]
To generate bounding boxes and dialog boxes using the Gradio demo, please follow these steps:

1. Upload Character Images
Begin by uploading the manga character images you want to use.

2. Draw Character Bounding Boxes
On the left panel, draw the bounding boxes for the characters (IP bounding boxes). Make sure the number of bounding boxes matches the number of uploaded character images.

3. Click "End Drawing IP Bbox"
Once you've drawn all the character bounding boxes, click the "End Drawing IP Bbox" button. This will transfer the character bounding boxes to the right panel (dialog bbox panel).

4. Draw Dialog Bounding Boxes (Optional)
On the right panel (dialog bbox panel), draw bounding boxes for dialogs if needed. Remember, dialog boxes should only be drawn on the dialog bbox panel (right side), not on the character bbox panel (left side).

5. Generate Images
After completing all bounding boxes, click the "Generate Images" button to create the output.

Tips for Better Quality:
1. Experiment with Prompts and Characters
Use a variety of prompts and character images to achieve diverse outputs.

2. Try Different Random Seeds
Experimenting with different seeds can significantly influence the output and help you find better results.

3. Be Patient
Generating high-quality samples may require several attempts and fine-tuning.

If you have additional questions or need further clarification, feel free to ask! 😊

**Comment by SoftologyPro** [comment]
Ok, thanks. Maybe add those more detailed instructions to the top of the gradio UI?

**Comment by Sonu788923** [comment]
How did you download the software

**Comment by jianzongwu** [comment]
> Ok, thanks. Maybe add those more detailed instructions to the top of the gradio UI?

We are working on an improved version of demo.
