### ISSUE TITLE
why use two tokenizer/text encoders to process text messages? 

### ISSUE THREAD

**Issue by sherlockma11** [jianzongwu/DiffSensei#12]
I just read the source code and it's terrific work. But I have a question, why use two tokenizer/text encoders to process text messages? One converts to 768 dimensions and the other converts to 1280 dimensions. And then concat it together at the end?

Thanks, and I'm also want to know if the training code will be open-sourced

**Comment by jianzongwu** [comment]
Hello, this design if from SDXL. It uses two text encoders to enhance the text information.

We are working on the open source of training code.
