### ISSUE TITLE
Demo results not matching showcased outputs for DiffSensei(default ones)

### ISSUE THREAD

**Issue by krigeta** [jianzongwu/DiffSensei#4]
I have followed the instructions to run the provided demo. While the project claims to generate manga panels using character images, the actual results from the demo are far from what has been showcased in the examples.

Here are the main issues I am facing:

The generated manga panels are not even close to the quality shown in the project’s repository or documentation.
The demo itself feels incomplete or poorly implemented, with significant gaps in usability and reproducibility.
I am attaching an example image that highlights the discrepancy. It would be great if you could provide clarity on:

How the showcased results were achieved. 
![Screenshot (11)](https://github.com/user-attachments/assets/00426bec-a3e6-4d50-81de-9d3721d7c66d)

Any specific settings or configurations needed to replicate those results.
Looking forward to your guidance or improvements in the demo.

**Comment by jianzongwu** [comment]
Thank you for bringing this to our attention and for sharing the example image—it helps us better understand the issues you're encountering.

The quality of generated manga panels can indeed vary depending on factors such as the character/dialog layout and the random seeds used. We are aware of the gaps in usability and reproducibility in the demo and are actively working on improvements to address these concerns.

We will improve the demo’s usability and ensuring more consistent and high-quality outputs. We will also provide additional examples and detailed guidance to help users achieve results closer to those showcased. Please bear with us as we work on these updates—we will notify you once the improvements are live.

Thank you for your patience and valuable feedback!

**Comment by deeplearn-art** [comment]
The panel resolution in your example is quite small, which could be a factor affecting the quality of the output.

**Comment by Sonu788923** [comment]
How did you run the program
